on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    services:
      nats:
        image: nats
        ports:
          - 4222:4222
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # Get values for cache paths to be used in later steps
      - name: Configure go caching
        id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-test-go-mod-${{ hashFiles('**/go.sum') }}

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-test-go-build-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test ./... -race -timeout 30s
