on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        # for now only support 1.21 because of loopvar experiment
        # go-version: [1.21.x, 1.22.x]
        go-version: [1.21.x]
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
    services:
      nats:
        image: nats
        ports:
          - 4222:4222
      nats-auth:
        image: ghcr.io/overmindtech/test-populated-nats:main
        # ports:
        #   - 4222:4222

      api-server:
        image: ghcr.io/overmindtech/test-populated-api-server:main
        env:
          # This is the URL of the nats-auth container above. Thankfully github
          # creates all service containers on the same network, and with a nice
          # network alias so we can use docker-provided DNS to have them talk to
          # one another
          NATS_URL: nats://nats-auth:4222
          DISABLE_KUBE: true
          API_SERVER_PGHOST: postgres
          API_SERVER_PGUSER: ci
          API_SERVER_PGPASSWORD: ci
          API_SERVER_PGDBNAME: ci
          ATLAS_DISABLE_SSL: true
        ports:
          - 8080:8080
        options: >-
          --restart always

      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ${{ matrix.os }}

    env:
      GOEXPERIMENT: loopvar

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.x
          check-latest: true

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -race -timeout 2m
        env:
          OVERMIND_NTE_ALLPERMS_DOMAIN: ${{ secrets.OVERMIND_NTE_ALLPERMS_DOMAIN }}
          OVERMIND_NTE_ALLPERMS_CLIENT_ID: ${{ secrets.OVERMIND_NTE_ALLPERMS_CLIENT_ID }}
          OVERMIND_NTE_ALLPERMS_CLIENT_SECRET: ${{ secrets.OVERMIND_NTE_ALLPERMS_CLIENT_SECRET }}
